theme = "github_dark_dimmed"
[keys.insert]
"S-ret" = ["goto_line_end", "move_char_right"]

[editor.gutters]
layout = ["diagnostics", "line-numbers", "spacer"]

[editor]
clipboard-provider = "x-clip"
default-yank-register = "+"
