[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
file-types = ["html"]
indent = { tab-width = 4, unit = "t" }
auto-format = false

[[language]]
name = "typescript"
file-types = ["js", "ts"]
indent = { tab-width = 4, unit = "t" }

# [language-server.typescript-language-server]
# args = ["--stdio"]

# [[language]]
# name = "javascript"
# file-types = ["js", "ts"]
# # language-servers = ["deno"]
# indent = { tab-width = 4, unit = "t" }

